yoshinori-teramura/freemarket_sample_53a

README.md

メルカリのDB設計
メルカリ作成に必須のため
とりあえず共有させてください。
レビューお願い致します。
creditDB
・カラムは後々追加前提です。

[WIP] README

---

Gemfile.lock
config/initializers/carrierwave.rb
db/schema.rb

修正しました。
本番環境で画像を投稿できるようにしたいです。

S3の画像の保存先【01】

---

app/assets/stylesheets/items.scss
app/views/devise/shared/_header.html.erb
app/views/items/index.html.erb
app/views/items/index.html.haml

What
トップページのヘッダー部分を部分テンプレートとして作成いたしました。
※リストの表示はまだです
Why
他のページでも使われるので先に作成しました。

トップページのヘッダー部分作成

---

app/assets/stylesheets/items.scss
app/views/items/index.html.haml

What
トップページのメインの内容
Why
リンク先などを考える際にも必要だから

Create main toppage

---

app/assets/javascripts/sell.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/sell.scss
app/controllers/sell_controller.rb
app/helpers/sell_helper.rb
app/views/sell/index.html.haml
config/routes.rb
test/controllers/sell_controller_test.rb

商品出品ページのマークアップ

---

app/views/items/index.html.haml

TOPページの商品出品ボタンに出品ページへのリンクを追加
画面遷移できるようにするため

出品ボタンに出品ページのリンクを追加

---

app/views/devise/sessions/new.html.haml
app/views/signup/registration.html.haml

必須項目では無いですが、個人的にくるくる画面を実装したくてしょうがなかったので。
キーとしての実装は必須項目が終わり次第、やろうと思います。
[実装画面](https://gyazo.com/82800bc8cec89f59fa8bc0d76251726d)

[WIP]google_recapthaの実装。画面のみ

---

app/assets/javascripts/sell.coffee
app/assets/javascripts/sell.js
app/assets/stylesheets/sell.scss
app/views/sell/index.html.haml

・価格計算
・カテゴリの切り替え
・商品出品の見た目を整えるため

商品出品画面の画面の挙動を追加

---

app/helpers/application_helper.rb

価格表示時のエラーを修正
item.priceのnullチェック漏れ

価格がnullの時のエラーを修正

---

app/assets/stylesheets/items.scss
app/assets/stylesheets/valid_error.scss
app/views/devise/shared/_header.html.haml

* レイアウト修正：ヘッダーの表示幅を1020pxに変更
* レスポンシプに対応していないので、標準サイズに変更
* マイページへのURL修正
URLが間違っていたので修正

ログイン中のヘッダーレイアウト修正

---

app/assets/javascripts/logout.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/logout.scss
app/controllers/logout_controller.rb
app/helpers/logout_helper.rb
app/views/devise/shared/_header.html.haml
app/views/logout/index.html.haml
app/views/mypages/_sidemenu.html.haml
config/routes.rb
test/controllers/logout_controller_test.rb

ログアウト画面の作成

---

app/views/items/show.html.haml
db/schema.rb

商品出品ページで入力した改行が商品詳細ページで改行されていないのを修正

商品詳細ページの修正：改行がされない

---

README.md
app/models/brand.rb
app/models/category.rb
app/models/item.rb
db/migrate/20191020062057_add_params_to_items.rb
db/schema.rb

* itemテーブルにカテゴリとブランドテーブルを紐付け
* itemテーブルに配送方法、商品情報の絡むを追加
* 商品にカテゴリとブランドを紐付け
* 商品に配送方法などの情報を保存する

itemsテーブルの更新

---

Gemfile
Gemfile.lock

Reverts yoshinori-teramura/freemarket_sample_53a#61

Revert "パンくずリストを実装02"

---

.vscode/settings.json
app/assets/javascripts/sell,validate.js
app/assets/javascripts/signup.validate.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/mypages.scss
app/assets/stylesheets/notice.scss
app/controllers/mypages_controller.rb
app/controllers/signup_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/views/items/index.html.haml
app/views/mypages/_sidemenu.html.haml
app/views/mypages/deliver_address.html.haml
app/views/mypages/email_password.html.haml
app/views/mypages/identification.haml
app/views/mypages/index.html.haml
app/views/mypages/profile.html.haml
app/views/mypages/sms_confirmation.html.haml
app/views/signup/address.html.haml
app/views/signup/credit.html.haml
config/routes.rb

ユーザー登録情報の更新画面の実装
・プロフィール
・発送元・届け先
・支払い方法
・メールパスワード
・本人情報
・電話番号の確認
必須機能
[イメージ](https://gyazo.com/1dace022d69fddb83bd3baa5444ebf01)

ユーザー情報の更新画面の実装

---

app/views/items/show.html.haml

Reverts yoshinori-teramura/freemarket_sample_53a#66

Revert "パンくずリストを実装04"

---

app/controllers/items_controller.rb
app/controllers/mypages_controller.rb
app/controllers/signup_controller.rb
app/models/item.rb

修正が間違っていたので戻します。

---

app/controllers/items_controller.rb
app/controllers/mypages_controller.rb
app/controllers/signup_controller.rb
app/models/item.rb

Reverts yoshinori-teramura/freemarket_sample_53a#72

Revert "修正が間違っていたので戻します。"

---

app/views/devise/shared/_header.html.haml
app/views/mypages/identification.haml
app/views/mypages/index.html.haml
config/breadcrumbs.rb

パンくずリストを実装06

---

app/controllers/items_controller.rb

商品詳細画面のエラー修正
`@same_category_items`が消えていたため

商品詳細画面のエラー修正

---

app/assets/javascripts/sell.validate.js
app/assets/stylesheets/mypages.scss
app/controllers/sell_controller.rb
app/models/item.rb
app/views/mypages/_sidemenu.html.haml
app/views/mypages/credit.html.haml
app/views/mypages/profile.html.haml
config/routes.rb

ユーザープロフィールの細かい部分はまだ修正します。
画像のvalidationも引き続き進めます。
[クレジットカード追加画面](https://gyazo.com/276e3a7673449c0e6e9da8bb6c52dd16)

credit登録画面とプロフィールの修正

---

app/assets/javascripts/sell.validate.js
app/assets/javascripts/signup.validate.js
app/assets/stylesheets/mypages.scss
app/views/mypages/profile.html.haml
app/views/sell/index.html.haml

・ユーザープロフィール画面の修正
[実装](https://gyazo.com/a9b64de77d00eeca7a3062066a92bc53)
・商品出品の金額validation
→数字以外はエラー・１０００万以上はエラー

[WIP]ユーザープロフィールの編集と商品出品画面の金額のvalidaton追加

---

app/assets/javascripts/sell.validate.js
app/assets/javascripts/signup.validate.js
app/controllers/sell_controller.rb
app/controllers/signup_controller.rb
app/views/sell/_form.html.haml
app/views/signup/address.html.haml
app/views/signup/registration.html.haml

新規登録画面・商品出品画像のバリデーション修正しました。
クレジット登録画面は今後変更するので修正してません。
[登録修正](https://gyazo.com/c0894692a78f65cb2f0ef6a7edf45b5b)
[商品画像](https://gyazo.com/a7afe80919862040d21cc4c099574de9)

新規登録画面のバリデーション修正と商品画像のバリデーション

---

app/assets/stylesheets/buy.scss
app/assets/stylesheets/items.scss
app/assets/stylesheets/modules/global.scss
app/views/buy/show.html.haml

全体的にレイアウトが崩れていたため、mixinでcssの定期用範囲を限定しました。

全体的なレイアウト修正

---

app/controllers/mypages_controller.rb
app/views/devise/shared/_header.html.haml
app/views/mypages/_sidemenu.html.haml
config/breadcrumbs.rb
config/routes.rb

ユーザ情報の設定にまつわるルーティングを変更
他ユーザ情報を変更できてしまう可能性があったため

別ユーザの情報を変更できてしまうのを修正

---

app/assets/javascripts/slide.js
app/assets/stylesheets/items.scss
app/views/items/index.html.haml
app/views/layouts/application.html.haml

トップページ画像の遷移
かっこいいから
[実装画面](https://gyazo.com/313632c908858a48c5f12804207b79e1)

トップページの画面遷移

---

app/assets/javascripts/slide.js
app/assets/stylesheets/items.scss
app/views/items/index.html.haml

矢印をクリック時の任意で画像遷移
せっかくなので
[実装](https://gyazo.com/6a6178fdfb6f20c56cc68dd9c249a5dc)

トップ画像自動遷移　追加実装

---

app/controllers/buy_controller.rb
app/views/buy/show.html.haml
config/routes.rb

What
payjpで商品購入・決済できるようにしました。
Why
クレジットカードの登録だけでなく決済もできるようにしないと意味ないため。
https://gyazo.com/757d4c394ef10dbc51a331143d71805f
https://gyazo.com/eb4b86da5e2e4894e7deb573e5cdde56

Setup payjp for purchase

---

app/views/mypages/credit.html.haml
config/routes.rb

マイページ＞支払い方法をクリック時にエラーが発生したため、ルーティングを修正

クレジットカード追加画面の修正

---

app/assets/stylesheets/credit.scss
app/views/credit/edit.html.haml

What
クレジットカード登録画面のレイアウトを修正しました
Why
統一感を出すため
https://gyazo.com/ed89a503598ee36aae20338cccc6e445

fix layout for credit

---

app/controllers/listings_controller.rb

出品した商品を全て表示するように変更

---

app/controllers/credit_controller.rb

クレジット登録に例外処理を追加

---

app/assets/stylesheets/mypages.scss
app/controllers/buy_controller.rb
app/controllers/mypages_controller.rb
app/helpers/items_helper.rb
app/models/buyer.rb
app/models/item.rb
app/views/items/show.html.haml
app/views/mypages/_bought_item.html.haml
app/views/mypages/_sidemenu.html.haml
app/views/mypages/index.html.haml
app/views/mypages/purchase.html.haml
app/views/mypages/purchased.html.haml
config/breadcrumbs.rb
config/routes.rb
db/migrate/20191104094305_create_buyers.rb
db/schema.rb
spec/factories/buyers.rb
spec/factories/categories.rb
spec/factories/items.rb
spec/models/buyer_spec.rb
spec/models/item_spec.rb

* 購入時に購入情報を記録
* 購入した商品のページに表示
* 単体テスト実装
* 誰が購入したかわからないため

購入した商品と購入履歴のページを実装

---

app/assets/stylesheets/categories.scss
app/controllers/categories_controller.rb
app/views/categories/index.html.haml
app/views/categories/show.html.haml

What
・カテゴリーページの各カテゴリーアイテムを表示するページのレイアウトを整えました
・未完成だったcategoryのshowのコントローラーを、全てのカテゴリーで機能するようにする為
Why
・各カテゴリーでアイテムを表示できると便利な為
https://gyazo.com/7d3065b2f8c576e0125e649bc931472b
https://gyazo.com/434e06ab2f54ecf211fd842aea8ae431

Fix category show
